### ISSUE TITLE
Is HttpBind not supported since Version 1.1.X?

### ISSUE THREAD

**Issue by naive924** [igniterealtime/openfire-pade-plugin#100]
Hi @deleolajide 

Could you tell me about http-bind?
For some reason, I want to turn off `openBridgeChannel: websocket` and use the existing `https://hostname:7443/http-bind/`.
When I tried it, it seemed that I got `org.jitsi.protocol.xmpp.colibri.exception.TimeoutException` when three or more people participate.
(There is no problem with 2 users)

* config.js
(https://hostname:7443/ofmeet/config.js)
https://gist.github.com/naive924/7d64160af504d0673983c7b70432f3d1

* Error
```
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - Jicofo 2020-11-26 17:16:47.546 重大: [56] org.jitsi.jicofo.AbstractChannelAllocator.log() ofmeet@conference.localhost/jvb - failed to allocate channels, will consider the bridge faulty: Timed out waiting for a response.
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - org.jitsi.protocol.xmpp.colibri.exception.TimeoutException: Timed out waiting for a response.
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.maybeThrowOperationFailed(ColibriConferenceImpl.java:342)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.createColibriChannels(ColibriConferenceImpl.java:282)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.protocol.xmpp.colibri.ColibriConference.createColibriChannels(ColibriConference.java:112)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.jicofo.ParticipantChannelAllocator.doAllocateChannels(ParticipantChannelAllocator.java:110)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.jicofo.AbstractChannelAllocator.allocateChannels(AbstractChannelAllocator.java:271)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.jicofo.AbstractChannelAllocator.doRun(AbstractChannelAllocator.java:190)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at org.jitsi.jicofo.AbstractChannelAllocator.run(AbstractChannelAllocator.java:150)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020.11.26 17:16:47 INFO  [Thread-40]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

* call https://hostname:7443/http-bind/
Call to http-bind succeeds.
![image](https://user-images.githubusercontent.com/6185430/100329691-5bf08a00-3011-11eb-90d2-bc0856158a11.png)

**Comment by deleolajide** [comment]
> For some reason, I want to turn off `openBridgeChannel: websocket` and use the existing `https://hostname:7443/http-bind/`.

It is needed by JVB2 Read [this](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md) to find out why you can't switch if off. To understand why there is no alternative for ofmeet, read [this](https://github.com/jitsi/jitsi-sctp/pull/3) 

If you want to switch off Openfire websockets in preference of http-bind, use this setting
![image](https://user-images.githubusercontent.com/110731/100340102-9981f280-2fd2-11eb-8b77-d2ca22646d55.png)

**Comment by naive924** [comment]
Thankyou for the explanation.
