### ISSUE TITLE
Timeout problem on communication between JiCoFo and JVB2 during startup

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#109]
On my evaluation stage, all work well. But on approval stage, participants can't initiate rooms.

I notice the following error messages in the log.
```
20201130-133222.724 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-133223.405 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] Exception in thread "Smack-Single Threaded Executor 0 (0)" java.lang.NullPointerException
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:484)
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient.access$300(MucClient.java:50)
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient$2.handleIQRequest(MucClient.java:466)
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.AbstractXMPPConnection$4.run(AbstractXMPPConnection.java:1188)
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20201130-133223.406 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.lang.Thread.run(Thread.java:748)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] SEVERE: [58] org.jivesoftware.smack.roster.Roster$5.processException: Exception reloading roster
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Waited for response using: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQT
ypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=SoKZX-15)), : fromFilter (OrFilter: (FromMatchesFilter (full): null, FromMatchesFilter (ignoreResourcepart): jvb@appr.xmpp.dnb.de, FromMatchesFilter (full): appr.xmpp.dnb.de)).
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:111)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.AbstractXMPPConnection$8.run(AbstractXMPPConnection.java:1594)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20201130-133223.408 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20201130-133223.409 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.lang.Thread.run(Thread.java:748)
20201130-133223.415 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [21] [hostname=appr.xmpp.dnb.de id=shard] MucClient.lambda$getConnectAndLoginCallable$7#619: Failed to join the MUCs.
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Waited for response using: IQReplyFilter: iqAndIdFilter (AndFilter: (OrFilter: (IQT
ypeFilter: type=error, IQTypeFilter: type=result), StanzaIdFilter: id=SoKZX-18)), : fromFilter (OrFilter: (FromMatchesFilter (full): conference.appr.xmpp.dnb.de)).
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:111)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:98)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:260)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:214)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:540)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:506)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeatures(ServiceDiscoveryManager.java:748)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeatures(ServiceDiscoveryManager.java:744)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.disco.ServiceDiscoveryManager.supportsFeature(ServiceDiscoveryManager.java:740)
20201130-133223.416 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.muc.MultiUserChatManager.providesMucService(MultiUserChatManager.java:361)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.muc.MultiUserChat.enter(MultiUserChat.java:311)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:498)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jivesoftware.smackx.muc.MultiUserChat.createOrJoin(MultiUserChat.java:444)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.join(MucClient.java:701)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient$MucWrapper.access$200(MucClient.java:632)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient.joinMucs(MucClient.java:322)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:615)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20201130-133223.417 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20201130-133223.418 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper]      at java.lang.Thread.run(Thread.java:748)
20201130-133227.714 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-133228.073 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [57] org.jivesoftware.smack.roster.Roster$PresencePacketListener.processStanza: Roster not loaded while processing Presence Stanza [to=jvb@appr.xmpp.dnb.de/3n417uq28,from=jvb@appr.xmpp.dnb.de/3n417uq28,
id=SoKZX-16,type=available,]
20201130-133232.715 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-133237.220 INFO  [Thread-20] [o.j.o.p.o.FocusPlugin] starting jitsiJicofoWrapper
20201130-133237.221 INFO  [Thread-20] [o.j.o.p.o.JitsiJicofoWrapper] Initializing Jitsi Focus Component (jicofo)...
20201130-133237.230 INFO  [Thread-20] [o.j.o.p.o.JitsiJicofoWrapper] allowed external component access
20201130-133237.247 INFO  [Thread-20] [o.j.o.p.o.JitsiJicofoWrapper] Successfully initialized Jitsi Focus Component (jicofo).
```
and after start, it's continous logging
```
0201130-134117.714 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-134122.713 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-134127.714 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-134132.713 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-134137.714 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.
20201130-134142.714 INFO  [Thread-26] [o.j.o.p.o.JvbPluginWrapper] WARNING: [30] [hostname=appr.xmpp.dnb.de id=shard] MucClient$MucWrapper.setPresenceExtensions#733: Cannot set presence extensions: no previous presence available.

```

**Comment by gjaekel** [comment]
Seems to be related to LDAP integration of the approval stage: As with the focus user, I request the WinAD-admin to provide me a user for the jvb. 

But it seems that this is the *wrong* way! I changed the JVM user within OFMeet to another and after this, the problem vanished.

**Comment by gjaekel** [comment]
closed in advance.
