### ISSUE TITLE
Push notifications are not working anymore

### ISSUE THREAD

**Issue by chagai95** [igniterealtime/openfire-pade-plugin#326]
This is what I see in the network tab:

http://cors-anywhere.herokuapp.com/corsdemo

![image](https://user-images.githubusercontent.com/31655082/116795283-2d9d3c00-aad4-11eb-9932-f42b6f24fffc.png)

this is the text:

This demo of CORS Anywhere should only be used for development purposes, see https://github.com/Rob--W/cors-anywhere/issues/301.

To temporarily unlock access to the demo, click on the following button: 
You currently have temporary access to the demo server.

So I guess you'll have to self host this proxy or find another alternative for the proxy?

**Comment by deleolajide** [comment]
Now that ofmeet is joined with the rest of Pade, push notification should be done server side as it is done with ConverseJS offline chat messages

**Comment by chagai95** [comment]
So this is a feature that is a feature that will no longer be possible to easily merge with upstream?

**Comment by deleolajide** [comment]
> So this is a feature that will no longer be possible to easily merge with upstream?

Good point. I had not thought about that. Not sure this any way to avoid a CORS proxy unless the browser vendors add the required headers to the push notification servers.

**Comment by gjaekel** [comment]
As a workaround, may we simulate to click?
```
<form><p>This demo of CORS Anywhere should only be used for development purposes, see <a href="https://github.com/Rob--W/cors-anywhere/issues/301">https://github.com/Rob--W/cors-anywhere/issues/301</a>.<p>To temporarily unlock access to the demo, click on the following button: <input type="submit" value="Request temporary access to the demo server"><input type="hidden" name="accessRequest" value="b1023df58f2dcbf8b374bed027574b1c459ad120de548a484d327cd3a965788d"></form>

```

**Comment by gjaekel** [comment]
May somebody describe me what is the task to do, i.e what is the original request, where is it fired in our sources and what's the problem this CORS proxy solves? It is possible to add such a proxy to our plugin which is written in Java (maybe https://github.com/shannah/cors-proxy/blob/master/src/main/java/com/codename1/corsproxy/CORSProxy.java ?)

**Comment by gjaekel** [comment]
Please also notice the conversation with @guusdk at https://discourse.igniterealtime.org/t/how-to-make-openfire-push-notifications-plugin-work/90103 
He points to  https://github.com/iNPUTmice/p2

**Comment by deleolajide** [comment]
> May somebody describe me what is the task to do, i.e what is the original request, where is it fired in our sources and what's the problem this CORS proxy solves?

The openfire push notification plugin implements [push notification](https://xmpp.org/extensions/xep-0357.html) for XMPP clients, but does not implement web push notifications. It only works with mobile clients that support the IOS and Android push notification services.

The push notification in ofmeet is an implementation of [web push notification](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) and does not involve XMPP. It involves the use of the web push API and a notification service provided by the web browser vendors. It also does not use a web server as the messages are pushed peer-to-peer to the notification servers directly. 

This works ok from a browser extension, but has an issue with regular web browser pages because the messages from the notification servers do not have CORS headers. The only way to fix this is to use a CORS proxy or send the messages from a web server.

**Comment by gjaekel** [comment]
@deleolajide Thank you for explanations!

Does this mean we should
* add a Java CORS proxy it inside the Pàdé plugin
* made this available via http(s?) with the restriction to be usable by "our" Jitsi WebClients, only.
* Set this proxy to be used by the WebPushNotification-lib bundled with our WebClient.

**Comment by deleolajide** [comment]
> It is possible to add such a proxy to our plugin which is written in Java

That defeats the purposes of sending messages peer-to-peer without using a webserver and merging the code upstream. Pade plugin already has web push notification that is being used for sending push messages to Converse users when they are offline. We simply use that instead of coding a CORS proxy

**Comment by gjaekel** [comment]
> That defeats the purposes of sending messages peer-to-peer without using a webserver 
At the moment, the feature don't work anymore because the use of the Demo CORS-proxy -- which is hardcode in the lib! -- was restricted to development purposes. One may enable it for a short time -- then, the feature is well working. but this is not usable for production.

> and merging the code upstream
That's for something completely different. And if I understand you in the right way, there will be no "solution" at all without anything "on the server" as long this is not solved by the browser vendors.

**Comment by chagai95** [comment]
https://github.com/subversivo58/lab/commit/656aca720ad5f9962949c5603a37df19af4349ef

**Comment by deleolajide** [comment]
This might be a better replacement for cors-anywhere

https://medium.com/bridgedxyz/cors-anywhere-for-everyone-free-reliable-cors-proxy-service-73507192714e

**Comment by gjaekel** [comment]
Do you remenber where to set the proxy for the lib?

**Comment by gjaekel** [comment]
Yields the same problem:
```
Access to fetch at 'https://cors.bridged.cc/https://fcm.googleapis.com:443/fcm/send/fzutPTxcJ00:APA91bEb9DR1J4KNTZ8NGl8xieDgIyqDLFRiFRkhDmfPPn1UC4ZrL1h2jC92ZTB0v9OxzbiSAIqn1mBoK0SEyrDOosY650PU8N-W7C2iux6xjPM--UdeIp0YjZ4c0f_v5FSO_mNnctMc' from origin 'https://miet.dnb.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by deleolajide** [comment]
It is not a drop-in replacement. You would need to do a bit more to construct the correct URL for this CORS proxy

**Comment by gjaekel** [comment]
> It is not a drop-in replacement. 

To my understanding, it states as one.

>You would need to do a bit more to construct the correct URL for this CORS proxy

Also, I don't get this from my quick look on the documentation. But I'll read more careful and maybe understand what to do;  @chagai95 will probably help me.

**Comment by deleolajide** [comment]
**If you use it drop-in without setting headers, you get this**

![image](https://user-images.githubusercontent.com/110731/117114735-20a67400-ad84-11eb-8774-6eef7419092d.png)

**If you set headers like this, then it works**

![image](https://user-images.githubusercontent.com/110731/117115024-7549ef00-ad84-11eb-898b-f873acaed537.png)

**Comment by gjaekel** [comment]
i.e. I have to figure out howto add _this_ header within the library?

**Comment by deleolajide** [comment]
> i.e. I have to figure out howto add _this_ header within the library?

👍

**Comment by gjaekel** [comment]
_There's somethings with headers a few lines ahead. Will play with this ..._

**Comment by gjaekel** [comment]
Fact: If the destination is a **Firefox** browser, notification (currently) works because it send the message to

```
https://updates.push.services.mozilla.com/wpush/v2/gAAAAABgWRAHmt3nMQr674lfvQF-v-FUcqcJ6wHXgxCRQoN4XHUznfTJbMWxLyIuYB1cjtIXDcHmAkdEamchyvXF3BKzRjRamcdbeuJwxbIpKyZ4f55PAdSy-bXr8iH5yn8_adkuMGGj8e_IRSOOjdhHxxgPDj4S1C4g0W98bZfxJSRHZm4EeKE
```
```
OPTIONS /wpush/v2/gAAAAABgWRAHmt3nMQr674lfvQF-v-FUcqcJ6wHXgxCRQoN4XHUznfTJbMWxLyIuYB1cjtIXDcHmAkdEamchyvXF3BKzRjRamcdbeuJwxbIpKyZ4f55PAdSy-bXr8iH5yn8_adkuMGGj8e_IRSOOjdhHxxgPDj4S1C4g0W98bZfxJSRHZm4EeKE HTTP/1.1
Host: updates.push.services.mozilla.com
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization,content-encoding,content-type,crypto-key,encryption,ttl
Origin: https://miet.dnb.de
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-Fetch-Dest: empty
Referer: https://miet.dnb.de/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de;q=0.8
```

**Comment by gjaekel** [comment]
At https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS it is written:

>    Note
>
>    As described below, the actual POST request **does not include** the Access-Control-Request-* headers; they are needed only for the OPTIONS request.

Might it be a bug of Chrome that this browser expect it, nevertheless for the POST request?

**Comment by gjaekel** [comment]
You solve this on a 3rd way by moving processing to the server side?

**Comment by deleolajide** [comment]
> You solve this on a 3rd way by moving processing to the server side?

Yes. See my original comment

>Now that ofmeet is joined with the rest of Pade, push notification should be done server side as it is done with ConverseJS offline chat messages

**Comment by gjaekel** [comment]
Will test it ASAP, maybe event this evening.

**Comment by gjaekel** [comment]
Sorry, but I get the same error as before

![image](https://user-images.githubusercontent.com/19855721/119033415-7b0f1980-b9ad-11eb-91e0-d31477e80d1f.png)

**Comment by gjaekel** [comment]
Because I use different domains for frontend and xmpp server, I had to setup a reverse proxy for the path `/rest/api/restapi/v1/meet`. Now, I get a `HTTP RC 400`

![image](https://user-images.githubusercontent.com/19855721/119038912-fbd11400-b9b3-11eb-881a-b82478c4ec48.png)

```
20210520-213409.448 ERROR [Jetty-QTP-BOSH-315] [o.i.m.MeetController] sendWebPush failed
{"payload":{"msgSubject":"DNB meetings EVAL (Pàdé-1.4.0-SNAPSHOT-20210426/Openfire-4.6.1)","msgBody":"jaekel invites you to join the room bastelkeller.","msgType":"meeting","url":"https://miet.dnb.de/raum/Bastelkeller"},"publicKey":"BArSjQRnAz5SpBUBRSBdkTYTRXAeXXSQOJ52YfuOgQVk>
org.jose4j.lang.InvalidKeyException: The given key (algorithm=ECDH) is not valid for SHA256withECDSA
        at org.jose4j.jws.BaseSignatureAlgorithm.initForSign(BaseSignatureAlgorithm.java:102) ~[jose4j-0.6.0.jar!/:?]
        at org.jose4j.jws.BaseSignatureAlgorithm.sign(BaseSignatureAlgorithm.java:73) ~[jose4j-0.6.0.jar!/:?]
        at org.jose4j.jws.EcdsaUsingShaAlgorithm.sign(EcdsaUsingShaAlgorithm.java:68) ~[jose4j-0.6.0.jar!/:?]
        at org.jose4j.jws.JsonWebSignature.sign(JsonWebSignature.java:164) ~[jose4j-0.6.0.jar!/:?]
        at org.jose4j.jws.JsonWebSignature.getCompactSerialization(JsonWebSignature.java:132) ~[jose4j-0.6.0.jar!/:?]
        at nl.martijndwars.webpush.PushService.sendAsync(PushService.java:170) ~[pade-1.4.1-SNAPSHOT.jar!/:?]
        at nl.martijndwars.webpush.PushService.send(PushService.java:110) ~[pade-1.4.1-SNAPSHOT.jar!/:?]
        at org.ifsoft.meet.MeetController.sendWebPush(MeetController.java:187) ~[pade-1.4.1-SNAPSHOT.jar!/:?]
        at org.ifsoft.meet.MeetService.sendWebPush(MeetService.java:144) ~[pade-1.4.1-SNAPSHOT.jar!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[jersey-server-1.19.4.jar!/:?]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[jersey-servlet-1.19.4.jar!/:?]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) ~[jersey-servlet-1.19.4.jar!/:?]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) ~[jersey-servlet-1.19.4.jar!/:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905) [jetty-util-9.4.35.v20201120.jar:9.4.35.v20201120]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.security.InvalidKeyException: Not an EC key: ECDH
        at sun.security.ec.ECKeyFactory.checkKey(ECKeyFactory.java:121) ~[sunec.jar:1.8.0_282]
        at sun.security.ec.ECKeyFactory.toECKey(ECKeyFactory.java:90) ~[sunec.jar:1.8.0_282]
        at sun.security.ec.ECDSASignature.engineInitSign(ECDSASignature.java:225) ~[sunec.jar:1.8.0_282]
        at sun.security.ec.ECDSASignature.engineInitSign(ECDSASignature.java:218) ~[sunec.jar:1.8.0_282]
        at java.security.Signature$Delegate.tryOperation(Signature.java:1286) ~[?:1.8.0_282]
        at java.security.Signature$Delegate.chooseProvider(Signature.java:1234) ~[?:1.8.0_282]
        at java.security.Signature$Delegate.engineInitSign(Signature.java:1332) ~[?:1.8.0_282]
        at java.security.Signature.initSign(Signature.java:621) ~[?:1.8.0_282]
        at org.jose4j.jws.BaseSignatureAlgorithm.initForSign(BaseSignatureAlgorithm.java:93) ~[jose4j-0.6.0.jar!/:?]

```

**Comment by gjaekel** [comment]
I need to setup a proxy because of
https://github.com/igniterealtime/openfire-pade-plugin/blob/44558baf76aee448c080661adfce00c89c69dac3/src/webapp/custom_ofmeet.js#L3470
Should we use something based on `APP.connection.options.bosh` here (replacing the protocol by `https`)? Because this will point to the XMPP server.

**Comment by gjaekel** [comment]
https://github.com/web-push-libs/webpush-java#api
>First, make sure you add the BouncyCastle security provider:
> `Security.addProvider(new BouncyCastleProvider());`
_can't grep this in the sources ..._

**Comment by gjaekel** [comment]
Added by try
```
    private MeetController() {
        int pos = Security.addProvider(new BouncyCastleProvider());
        Log.info("BouncyCastleProvider registered at {}", pos);
    }
```
but got
```
20210521-144119.959 INFO  [Jetty-QTP-BOSH-136] [o.i.m.MeetController] BouncyCastleProvider registered at -1
```
and `-1` means that it's already registered :frowning_face:

**Comment by deleolajide** [comment]
I have removed dependency on jdk14. 

Try build after this commit - https://github.com/igniterealtime/openfire-pade-plugin/commit/398845d5bf6f36c1a7456fb0884ade1303a84238

**Comment by gjaekel** [comment]
No difference. To my eyes, with the changes in `pom.xml` this build just don't include the BouncyCastle relevant libs `bc*.jar` anymore. I already try many variants of this: Removing or replacing the `...15on..` versions by `...15to18...` but without any success.

To me, the error seems comparable to https://github.com/web-push-libs/webpush-java/issues/5: The sun jce lib don't know about  the string "ECDH" and expect "EC". Maybe we shout file this as issue to @martijndwars @ https://github.com/web-push-libs

**Comment by deleolajide** [comment]
> Maybe we shout file this as issue to @martijndwars @ https://github.com/web-push-libs

The source code is inside Pade here - https://github.com/igniterealtime/openfire-pade-plugin/tree/master/src/java/nl/martijndwars/webpush

Have a look and see what is not working for you and change it.

I can replicate the problem, so I don't know what to fix. It works ok for me both in Windows and on my Linux Docker. 

![image](https://user-images.githubusercontent.com/110731/119181977-401eeb80-ba6a-11eb-80bb-7811c33ab692.png)

and

![image](https://user-images.githubusercontent.com/110731/119182070-604eaa80-ba6a-11eb-97a9-40c68d08271a.png)

**Comment by gjaekel** [comment]
I already located this, see my snipped above. I don't think there's any mistage or issue in your high-level code.

I wonder if it isn't related to the version and flavor of the JVM! I'm using AdoptOpenJDK 8u282. There at least 3 issues about `java.security.InvalidKeyException: Not an EC key: ECDH` in the upstream repository. I try to contact the author.

**Comment by deleolajide** [comment]
As suggested, I have used config.bosh instead of location.host. For me, both are pade.chat

>Should we use something based on APP.connection.options.bosh here (replacing the protocol by https)? Because this will point to the XMPP server.
