### ISSUE TITLE
Pade 1.6.1 install on Openfire 4.7.1 error

### ISSUE THREAD

**Issue by ll3N1GmAll** [igniterealtime/openfire-pade-plugin#387]
We have successfully installed the Pade plugin v1.6.1 on Openfire v4.7.1; but when the "Pade" button is clicked on the menu the page that comes up only shows the following error text:

Exception:
java.lang.NullPointerException
	at org.jivesoftware.openfire.plugin.pade.ofmeet_002dsummary_jsp._jspService(ofmeet_002dsummary_jsp.java:158)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:462)
	at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:234)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:73)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:49)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:234)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Looking in the logs I see the following:**
2022.02.23 15:27:39 ERROR [pool-2661-thread-1]: org.jivesoftware.openfire.muc.MultiUserChatManager - A database exception occurred while trying to load the ID for MUC service 'lobby' from the database.
java.sql.SQLSyntaxErrorException: Table 'openfire.ofMucService' doesn't exist
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28.jar:8.0.28]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.9.0.jar:2.9.0]
    at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.9.0.jar:2.9.0]
    at org.jivesoftware.openfire.muc.MultiUserChatManager.loadServiceID(MultiUserChatManager.java:600) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.muc.MultiUserChatManager.getMultiUserChatServiceID(MultiUserChatManager.java:491) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.muc.spi.MUCPersistenceManager.loadRoomsFromDB(MUCPersistenceManager.java:623) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.muc.spi.MultiUserChatServiceImpl.start(MultiUserChatServiceImpl.java:2676) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.component.InternalComponentManager.addComponent(InternalComponentManager.java:192) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.muc.MultiUserChatManager.registerMultiUserChatService(MultiUserChatManager.java:186) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.muc.MultiUserChatManager.registerMultiUserChatService(MultiUserChatManager.java:161) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.muc.MultiUserChatManager.createMultiUserChatService(MultiUserChatManager.java:288) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.plugin.ofmeet.LobbyMuc.initialize(LobbyMuc.java:46) [pade-1.6.1.jar:?]
    at org.jivesoftware.openfire.plugin.ofmeet.OfMeetPlugin.initializePlugin(OfMeetPlugin.java:316) [pade-1.6.1.jar:?]
    at uk.ifsoft.openfire.plugins.pade.PadePlugin.initializePlugin(PadePlugin.java:183) [pade-1.6.1.jar:?]
    at org.jivesoftware.openfire.container.PluginManager.loadPlugin(PluginManager.java:637) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:375) [xmppserver-4.7.1.jar:4.7.1]
    at org.jivesoftware.openfire.container.PluginMonitor$MonitorTask$4.call(PluginMonitor.java:363) [xmppserver-4.7.1.jar:4.7.1]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by gjaekel** [comment]
Is this a "fresh install" or an upgrade? To get more information, please provide the (shortened, compressed) `all.log` of the full startup of Openfire.

**Comment by ll3N1GmAll** [comment]
This is a fresh install; although I have uninstalled and reinstalled Pade a few times to see if that would resolve the issue. This is a new Openfire install as well. 

I will look at how to acquire the all.log file you are requesting and report back. Thank you for your assistance.

**Comment by gjaekel** [comment]
Seems to be a problem with the database setup. Do you use the internal or already an external database? From my instinct, we may have an "initial setup" issue here - most of us are long-time users and just upgrade. And I know about there's a full "QA integration test" running anywhere ...

**Comment by ll3N1GmAll** [comment]
[openfire.log](https://github.com/igniterealtime/openfire-pade-plugin/files/8130404/openfire.log)

I believe the correct the log file is attached and I believe I am using an internal database. I will look into how to search the database for tables and report back with what I find. Thank you again for your help.

**Comment by gjaekel** [comment]
> ... I believe I am using an internal database ...

The log tells about an MySQL database (-driver)
```
2022.02.20 22:18:37 ^[[1;31mERROR^[[m [Thread-22]: org.jivesoftware.openfire.muc.MultiUserChatManager - An unexpected exception occurred while trying to load all MUC services from the database.
java.sql.SQLSyntaxErrorException: Table 'openfire.ofMucService' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.jivesoftware.openfire.muc.MultiUserChatManager.loadServices(MultiUserChatManager.java:519) [xmppserver-4.7.1.jar:4.7.1]
        at org.jivesoftware.openfire.muc.MultiUserChatManager.start(MultiUserChatManager.java:107) [xmppserver-4.7.1.jar:4.7.1]
        at org.jivesoftware.openfire.XMPPServer.startModules(XMPPServer.java:924) [xmppserver-4.7.1.jar:4.7.1]
        at org.jivesoftware.openfire.XMPPServer.access$600(XMPPServer.java:159) [xmppserver-4.7.1.jar:4.7.1]
        at org.jivesoftware.openfire.XMPPServer$1.run(XMPPServer.java:678) [xmppserver-4.7.1.jar:4.7.1]
```
Maybe you start to switch to an external database but didn't initialize that.

**Comment by ll3N1GmAll** [comment]
I followed the initial setup instructions. If this indicates an external DB, then I must've been mistaken.

**Comment by gjaekel** [comment]
If using the internal DB, `.../conf/openfire.xml` must contain the section
```
  <connectionProvider> 
    <className>org.jivesoftware.database.EmbeddedConnectionProvider</className> 
  </connectionProvider>  
```
I guess yours already contain
```
  <connectionProvider> 
    <className>org.jivesoftware.database.DefaultConnectionProvider</className> 
  </connectionProvider>  
  <database> 
    <defaultProvider> 
      <driver>com.mysql.cj.jdbc.Driver</driver>  
[...]
```

**Comment by ll3N1GmAll** [comment]
You are correct. I am using an external MariaDB database.

**Comment by ll3N1GmAll** [comment]
I see the file at ..../resources/database/openfire_mysql.sql. How do I run this script? Thanks again for your assistance with this.

**Comment by gjaekel** [comment]
There's certainly no problem to use _MariaDB_ as a drop-in for _MySQL_.
> MariaDB [(none)]> database openfire

SQL-Syntax is `use <database>;` or start your mysql-shell by `mysql [-D] <database>`

Did you read the docs, e.g. https://download.igniterealtime.org/openfire/docs/latest/documentation/database.html#mysql ?

L.373 and L.377 are *INSERT* statements and the fail of the last one will probably cause the application error. 
```
# Entry for admin user
INSERT INTO ofUser (username, plainPassword, name, email, creationDate, modificationDate)
    VALUES ('admin', 'admin', 'Administrator', 'admin@example.com', '0', '0');

# Entry for default conference service
INSERT INTO ofMucService (serviceID, subdomain, isHidden) VALUES (1, 'conference', 0);
```

Because the DDL-script don't contain a `USE` statement and you maybe don't create and request a certain database while executing the script, the database tables might be created "somewhere" -- maybe on a default or the internal database named `mysql`?

**Comment by gjaekel** [comment]
May we close this?

**Comment by ll3N1GmAll** [comment]
I now get this error when running the DB script after having successfully selected the openfire DB.

MariaDB [openfire]> source /usr/share/openfire/resources/database/openfire_mysql.sql
ERROR 2006 (HY000) at line 2 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': MySQL server has gone a  way
No connection. Trying to reconnect...
Connection id:    1298
Current database: openfire

ERROR 1050 (42S01) at line 2 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofUser' already   exists
ERROR 1050 (42S01) at line 18 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofUserProp' alr  eady exists
ERROR 1050 (42S01) at line 25 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofUserFlag' alr  eady exists
ERROR 1050 (42S01) at line 35 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofOffline' alre  ady exists
ERROR 1050 (42S01) at line 44 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPresence' alr  eady exists
ERROR 1050 (42S01) at line 51 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofRoster' alrea  dy exists
ERROR 1050 (42S01) at line 65 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofRosterGroups'   already exists
ERROR 1050 (42S01) at line 73 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofVCard' alread  y exists
ERROR 1050 (42S01) at line 79 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofGroup' alread  y exists
ERROR 1050 (42S01) at line 85 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofGroupProp' al  ready exists
ERROR 1050 (42S01) at line 92 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofGroupUser' al  ready exists
ERROR 1050 (42S01) at line 99 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofID' already e  xists
ERROR 1050 (42S01) at line 105 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofProperty' al  ready exists
ERROR 1050 (42S01) at line 114 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofVersion' alr  eady exists
ERROR 1071 (42000) at line 120 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Specified key was too   long; max key length is 767 bytes
ERROR 1071 (42000) at line 128 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Specified key was too   long; max key length is 767 bytes
ERROR 1050 (42S01) at line 135 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPrivacyList'   already exists
ERROR 1071 (42000) at line 144 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Specified key was too   long; max key length is 767 bytes
ERROR 1050 (42S01) at line 150 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofSecurityAudi  tLog' already exists
ERROR 1071 (42000) at line 164 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Specified key was too   long; max key length is 767 bytes
ERROR 1050 (42S01) at line 173 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofMucServicePr  op' already exists
ERROR 1050 (42S01) at line 180 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofMucRoom' alr  eady exists
ERROR 1050 (42S01) at line 214 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofMucRoomProp'   already exists
ERROR 1050 (42S01) at line 221 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofMucAffiliati  on' already exists
ERROR 1050 (42S01) at line 228 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofMucMember' a  lready exists
ERROR 1050 (42S01) at line 240 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofMucConversat  ionLog' already exists
ERROR 1050 (42S01) at line 255 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubNode'   already exists
ERROR 1050 (42S01) at line 288 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubNodeJI  Ds' already exists
ERROR 1050 (42S01) at line 296 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubNodeGr  oups' already exists
ERROR 1050 (42S01) at line 303 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubAffili  ation' already exists
ERROR 1050 (42S01) at line 311 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubItem'   already exists
ERROR 1050 (42S01) at line 321 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubSubscr  iption' already exists
ERROR 1050 (42S01) at line 340 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'ofPubsubDefaul  tConf' already exists
ERROR 1062 (23000) at line 364 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry '18'   for key 'PRIMARY'
ERROR 1062 (23000) at line 365 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry '19'   for key 'PRIMARY'
ERROR 1062 (23000) at line 366 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry '23'   for key 'PRIMARY'
ERROR 1062 (23000) at line 367 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry '26'   for key 'PRIMARY'
ERROR 1062 (23000) at line 368 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry '27'   for key 'PRIMARY'
ERROR 1062 (23000) at line 370 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry 'open  fire' for key 'PRIMARY'
ERROR 1062 (23000) at line 373 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Duplicate entry 'admi  n' for key 'PRIMARY'
ERROR 1146 (42S02) at line 377 in file: '/usr/share/openfire/resources/database/openfire_mysql.sql': Table 'openfire.ofMuc  Service' doesn't exist

**Comment by gjaekel** [comment]
Seems that you run the DDL script at least a second time against the database `openfire` because most of the tables exit. Anyway --  as you (too) can easily see by inspecting the file -- the at least one which is missing is **not** created at L164 (`CREATE TABLE ofMucService (... ` because of an error. The same holds for other tables as well.

Maybe you're not using a recent Version of MariaDB (for MySQL, you need at least 5.7) or recent parameters for the Storage-Engine (compare e.g. to https://dba.stackexchange.com/questions/231219/mariadb-10-1-38-specified-key-was-too-long-max-key-length-is-767-bytes)

**Comment by deleolajide** [comment]
This does not seem to be a Pade issue. I am closing it now.
