### ISSUE TITLE
Thread leak in Websocket Proxy

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#395]
Using Pàdé-1.6.x, I discovered we have a serious thread leak at the websocket proxy. After some time, we end up in exhausing a pool.

From the users point of view, this will lead to effects like a dysfunction of the focus feature (blue frame not changing, no speaker stats) or missing adjustment of connection bandwith (low-quality cam or screenshare resolution)

```
20220309-143518.521 INFO  [Jetty-QTP-BOSH-248295] [o.j.o.p.o.OfMeetPlugin] JvbSocketCreator /colibri-ws/ofmeet/506bb990495f7a6e/3ffe2519?pwd=5lop60ucc4u9b9ci38s19csj0q pwd=5lop60ucc4u9b9ci38s19csj0q
20220309-143518.521 INFO  [Jetty-QTP-BOSH-248295] [ProxyConnection] ProxyConnection ws://10.10.1.146:8180/colibri-ws/ofmeet/506bb990495f7a6e/3ffe2519?pwd=5lop60ucc4u9b9ci38s19csj0q []
20220309-143518.522 ERROR [Jetty-QTP-BOSH-248295] [ProxyConnection] ProxyConnection ws://10.10.1.146:8180/colibri-ws/ofmeet/506bb990495f7a6e/3ffe2519?pwd=5lop60ucc4u9b9ci38s19csj0q
java.lang.IllegalStateException: Insufficient configured threads: required=1024 < max=1024 for QueuedThreadPool[ProxyConnection-HttpClient]@5de869e9{STARTED,1<=1003<=1024,i=0,r=-1,q=0}[ReservedThreadExecutor@56042d49{s=0/20,p=0}]
        at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:165) ~[jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:141) ~[jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:191) ~[jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:255) ~[jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
        at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.doStart(AbstractConnectorHttpClientTransport.java:64) ~[jetty-client-9.4.43.v20210629.jar:9.4.43.v20210629] 
```

I investigate a thread dump of an OpenFire instance runnig about 1d6h:
```
# su openfire jcmd $(jps -l | grep org.jivesoftware.openfire.starter.ServerStarter | cut -d ' ' -f 1)  Thread.print >openfire.threaddump
# grep "HttpClient@" openfire.threaddump | head
"HttpClient@f26ad70-scheduler-1" #3898 prio=5 os_prio=0 cpu=0.78ms elapsed=108261.05s tid=0x0000562455d6e720 nid=0x1624 waiting on condition  [0x00007fafcd18c000]
"HttpClient@318a21c0-scheduler-1" #3901 prio=5 os_prio=0 cpu=0.41ms elapsed=108261.04s tid=0x0000562455e03d50 nid=0x162a waiting on condition  [0x00007fafc2ffa000]
"HttpClient@bc84e2e-scheduler-1" #3908 prio=5 os_prio=0 cpu=0.50ms elapsed=108260.60s tid=0x00005624530123f0 nid=0x16d6 waiting on condition  [0x00007fafbe9f7000]
"HttpClient@40902612-scheduler-1" #3922 prio=5 os_prio=0 cpu=0.36ms elapsed=108259.89s tid=0x00005624561a3840 nid=0x1726 waiting on condition  [0x00007fafb9ffc000]
"HttpClient@1bfa6bd4-scheduler-1" #3923 prio=5 os_prio=0 cpu=0.24ms elapsed=108259.89s tid=0x00005624561a3200 nid=0x1727 waiting on condition  [0x00007fafb7df8000]
"HttpClient@702b4610-scheduler-1" #3936 prio=5 os_prio=0 cpu=0.40ms elapsed=108256.43s tid=0x0000562456304200 nid=0x1776 waiting on condition  [0x00007fafc4cf7000]
"HttpClient@6aea89bb-scheduler-1" #3949 prio=5 os_prio=0 cpu=0.62ms elapsed=108252.34s tid=0x0000562455eb8470 nid=0x17a7 waiting on condition  [0x00007fafbf3fc000]
"HttpClient@3044e3af-scheduler-1" #3968 prio=5 os_prio=0 cpu=0.21ms elapsed=108240.49s tid=0x00005624561c33d0 nid=0x18a3 waiting on condition  [0x00007fafad5fd000]
"HttpClient@2e04ecb8-scheduler-1" #3971 prio=5 os_prio=0 cpu=0.20ms elapsed=108240.42s tid=0x00005624560cf9f0 nid=0x18a9 waiting on condition  [0x00007fafc19fe000]
"HttpClient@601835a1-scheduler-1" #3977 prio=5 os_prio=0 cpu=0.49ms elapsed=108240.12s tid=0x00005624560b3170 nid=0x18d2 waiting on condition  [0x00007fafad3fc000]                                                                                                   20220310-212959
# grep "HttpClient@" openfire.threaddump -c
378
# awk -v RS= '/HttpClient@/ { print; exit }' openfire.threaddump 
"HttpClient@f26ad70-scheduler-1" #3898 prio=5 os_prio=0 cpu=0.78ms elapsed=108261.05s tid=0x0000562455d6e720 nid=0x1624 waiting on condition  [0x00007fafcd18c000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
	- parking to wait for  <0x00000000f34ddbb8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.2/AbstractQueuedSynchronizer.java:506)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.2/AbstractQueuedSynchronizer.java:1623)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.2/ScheduledThreadPoolExecutor.java:1170)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@17.0.2/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@17.0.2/ThreadPoolExecutor.java:1062)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1122)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
# grep "ProxyConnection-HttpClient" openfire.threaddump | head
"ProxyConnection-HttpClient-3897" #3897 prio=5 os_prio=0 cpu=186.83ms elapsed=108261.05s tid=0x0000562455d5d6d0 nid=0x1623 runnable  [0x00007fafc47fc000]
"ProxyConnection-HttpClient-3900" #3900 prio=5 os_prio=0 cpu=162.69ms elapsed=108261.04s tid=0x0000562455dffd00 nid=0x1629 runnable  [0x00007fafc3ffc000]
"ProxyConnection-HttpClient-3902" #3902 prio=5 os_prio=0 cpu=115.96ms elapsed=108261.01s tid=0x0000562455e10510 nid=0x163e runnable  [0x00007fafbfbfa000]
"ProxyConnection-HttpClient-3918" #3918 prio=5 os_prio=0 cpu=46.80ms elapsed=108259.90s tid=0x00005624561959a0 nid=0x1723 runnable  [0x00007fafbd7fd000]
"ProxyConnection-HttpClient-3920" #3920 prio=5 os_prio=0 cpu=24.39ms elapsed=108259.89s tid=0x000056245581b6d0 nid=0x1724 runnable  [0x00007fafbb1f2000]
"ProxyConnection-HttpClient-3967" #3967 prio=5 os_prio=0 cpu=31.32ms elapsed=108240.49s tid=0x00005624561c3c20 nid=0x18a2 runnable  [0x00007fafabafe000]
"ProxyConnection-HttpClient-3970" #3970 prio=5 os_prio=0 cpu=109.20ms elapsed=108240.42s tid=0x00005624556c3d90 nid=0x18a8 runnable  [0x00007fafc7afb000]
"ProxyConnection-HttpClient-3984" #3984 prio=5 os_prio=0 cpu=95.46ms elapsed=108235.37s tid=0x0000562456131fa0 nid=0x1930 runnable  [0x00007fafb89fe000]
"ProxyConnection-HttpClient-3985" #3985 prio=5 os_prio=0 cpu=88.94ms elapsed=108235.36s tid=0x00005624551010a0 nid=0x1931 runnable  [0x00007fafb3bfe000]
"ProxyConnection-HttpClient-3997" #3997 prio=5 os_prio=0 cpu=85.03ms elapsed=108231.09s tid=0x00005624522e30b0 nid=0x196b runnable  [0x00007fafbdbfe000]                                                                                                              20220310-213150
# grep "ProxyConnection-HttpClient" openfire.threaddump -c
378
# awk -v RS= '/ProxyConnection-HttpClient/ { print; exit }' openfire.threaddump 
"ProxyConnection-HttpClient-3897" #3897 prio=5 os_prio=0 cpu=186.83ms elapsed=108261.05s tid=0x0000562455d5d6d0 nid=0x1623 runnable  [0x00007fafc47fc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@17.0.2/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@17.0.2/EPollSelectorImpl.java:118)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.2/SelectorImpl.java:129)
	- locked <0x00000000f34f0240> (a sun.nio.ch.Util$2)
	- locked <0x00000000f34f01f0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@17.0.2/SelectorImpl.java:146)
	at org.eclipse.jetty.io.ManagedSelector.nioSelect(ManagedSelector.java:183)
	at org.eclipse.jetty.io.ManagedSelector.select(ManagedSelector.java:190)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:606)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:543)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:362)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:186)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```
The number of threads seems to "comparable corresponds" to the number of served participants so far:
![image](https://user-images.githubusercontent.com/19855721/157749835-655f0cd6-cfbd-453f-8fae-94bdbd7846e3.png)

**Comment by gjaekel** [comment]
From symmetry, we may forgot to call `httpClient.stop()` at
https://github.com/igniterealtime/openfire-pade-plugin/blob/6f36d5ace95a3b4fee8b7925e4ad57d05da5faee/src/java/org/ifsoft/websockets/ProxyConnection.java#L106-L118
because it's startet before the wsClient at
https://github.com/igniterealtime/openfire-pade-plugin/blob/6f36d5ace95a3b4fee8b7925e4ad57d05da5faee/src/java/org/ifsoft/websockets/ProxyConnection.java#L71-L73

**Comment by deleolajide** [comment]
Maybe [this](https://github.com/igniterealtime/openfire-pade-plugin/commit/f86411ccb18ed7ee4f7cdf2786d3cfea72e0912c) might fix it as suggested

**Comment by gjaekel** [comment]
Thank you. Will check it using the snapshot build, probably right tomorrow.

**Comment by gjaekel** [comment]
Here a part of the Life Thread View recording a short 2-participants meeting:
![image](https://user-images.githubusercontent.com/19855721/157821954-5fc9d82c-21b7-4741-a36c-43661c4db92c.png)
Now, the threads under discussion disappear.
