### ISSUE TITLE
Implement server-side login Jitsi Meet Polls

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#403]
Port code from Lua to Java

See https://github.com/jitsi/jitsi-meet/blob/68eb0795eb6a87189e27001d2e95c701536dac3f/resources/prosody-plugins/mod_polls.lua

**Comment by gjaekel** [comment]
Big problems:
* There's no name (owner?) shown for the polls
* How to close and get rid of messages in the WebClients user interface?
* Polls seems to be persisted at room properties. But the opened polls propagate to *every* existing room, esp. to the pinned ones.

Up to now, there a at least three "nonsense votings" lingering around from some users quick evaluation. How to get rid of them at all, maybe by an SQL statement?

**Comment by gjaekel** [comment]
BTW: I get an exception at the AdminUI at `plugins/rawpropertyeditor/groupchat-propertiesplugin.jsp` on every empty(?) pinned room, but this is an OpenFire / RawProperty-Plugin issue:
```
java.lang.IncompatibleClassChangeError: Found class org.jivesoftware.openfire.muc.MUCRoom, but interface was expected
	at org.jivesoftware.openfire.plugin.RawPropertyEditorPlugin.getAndCheckGroupChat(RawPropertyEditorPlugin.java:129)
	at org.jivesoftware.openfire.plugin.RawPropertyEditorPlugin.getGroupChatProperties(RawPropertyEditorPlugin.java:140)
	at org.jivesoftware.openfire.plugin.rawpropertyeditor.groupchat_002dpropertiesplugin_jsp._jspService(groupchat_002dpropertiesplugin_jsp.java:156)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:462)
	at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:234)
```

**Comment by gjaekel** [comment]
Observation: I found the poll data entries also at the special "focus" room. I delete it there and since this it seems that a client starts with an empty poll panel at least on a new room.

**Comment by gjaekel** [comment]
But for some reason the "three existing" polls appear at every room, even non-sticky new ones. This was reported by one of our users and verified by me.

**Comment by deleolajide** [comment]
>But for some reason the "three existing" polls appear at every room, even non-sticky new one

Unfortunately, I can't reproduce this. MUC Properties are cached by Openfire. You might want to reduce the expiry time otherwise, the next time a non-sticky room is used, the non-expired polls will be sent to each participant when they join.

I have added additional code for making sure focus user is not sent polls data

https://github.com/igniterealtime/openfire-pade-plugin/commit/c0daaf81d81bf6fccddf65c8274cb119e902d6df

**Comment by gjaekel** [comment]
Thank you in advance. Unfortunately I had have no time yet to investigate how to actually produce the issue. Will report about later ...

**Comment by gjaekel** [comment]
Snapshot installed in production.

**Comment by gjaekel** [comment]
Observation: Using the properties URL from history, e.g. `https://<admin-ui>/plugins/rawpropertyeditor/groupchat-propertiesplugin.jsp?roomJID=_%40conference.xmpp.dnb.de&create=false`, the property with the vote data is still accessible, even it the room has been left and closed down, i.e. disappear from the overview. And on re-using this room name, the vote also re-appear.

**Comment by deleolajide** [comment]
It might make sense to delete the poll when the room is destroyed in Openfire

**Comment by deleolajide** [comment]
[This commit](https://github.com/igniterealtime/openfire-pade-plugin/commit/b3581f8dbff6efe9757908c0b1185fdf8f256b84) will remove all room polls when the room is destroyed. However, the data is cached and the poll will still be available  if room is re-used before the cache expires

**Comment by gjaekel** [comment]
Can't believe: The call of `props.remove(key)` will not clear it from the cache?!? Then `props.put(key,"")` should made it unusable at least.
