### ISSUE TITLE
SIP not working?

### ISSUE THREAD

**Issue by grego1981** [igniterealtime/openfire-pade-plugin#75]
I have configured the SIP account to register on my asterisk server, but no attempt is made from the server to connect and thus no interface in jitsi invite a number. Do I need to configure anything else to make it work?

![image](https://user-images.githubusercontent.com/9021998/96216856-fc22b000-0f89-11eb-8fbd-b2728fdb96b2.png)

**Comment by deleolajide** [comment]
You need the [ofgasi plugin](https://github.com/igniterealtime/openfire-pade-plugin/releases/download/1.0.0/ofgasi.jar). However, please note that I don't use it and have not tested it as I don't have a SIP server.

**Comment by grego1981** [comment]
I tried the attached and have compiled the plugin from the github code, but it doesn't work... If it helps this is an error related to this, most likely, it seems that no SIP server (asterisk) IP is passed on for registration...

2020.10.16 13:43:43 net.java.sip.communicator.impl.protocol.sip.SipLogger - Error from the JAIN-SIP stack: Invalid argument address = ::0 port = 5060 transport = UDP
2020.10.16 13:43:43 net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection - Failed to create a Register request.
java.lang.NullPointerException: null
at org.jitsi.impl.osgi.framework.BundleContextImpl.getService(BundleContextImpl.java:126) ~[jitsi-android-osgi-1.0-20190327.160432-3.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipActivator.getVersionService(SipActivator.java:255) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getSipCommUserAgentHeader(ProtocolProviderServiceSipImpl.java:2132) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.attachScSpecifics(SipMessageFactory.java:529) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createRequest(SipMessageFactory.java:205) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createRegisterRequest(SipMessageFactory.java:1097) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:268) [jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.registerUsingNextAddress(ProtocolProviderServiceSipImpl.java:2737) [jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.register(ProtocolProviderServiceSipImpl.java:441) [jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59) [jigasi-1.1-20190806.132856-49.jar!/:?]
2020.10.16 13:43:45 net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl - Cannot send register!
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to generate a from header for our register request.
at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:301) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.registerUsingNextAddress(ProtocolProviderServiceSipImpl.java:2737) [jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.register(ProtocolProviderServiceSipImpl.java:441) [jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59) [jigasi-1.1-20190806.132856-49.jar!/:?]
Caused by: java.lang.NullPointerException
at org.jitsi.impl.osgi.framework.BundleContextImpl.getService(BundleContextImpl.java:126) ~[jitsi-android-osgi-1.0-20190327.160432-3.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipActivator.getVersionService(SipActivator.java:255) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getSipCommUserAgentHeader(ProtocolProviderServiceSipImpl.java:2132) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.attachScSpecifics(SipMessageFactory.java:529) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createRequest(SipMessageFactory.java:205) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createRegisterRequest(SipMessageFactory.java:1097) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
at net.java.sip.communicator.impl.protocol.sip.SipRegistrarConnection.register(SipRegistrarConnection.java:268) ~[jitsi-protocol-sip-2.13.cb5485e.jar!/:?]
... 3 more
2020.10.16 13:43:45 net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl - No address found for ProtocolProviderServiceSipImpl(4545@10.0.1.20 (SIP))

**Comment by deleolajide** [comment]
got to https://community.jitsi.org/ for help

**Comment by grego1981** [comment]
I believe it is not a jitsi error, it seems the configuration from the meetings menu is not creating the correct header or not using the SIP server IP as saved. Is there a way to intervene to the sip config file that is passed on to jitsi?

**Comment by deleolajide** [comment]
> Is there a way to intervene to the sip config file that is passed on to jitsi?

https://github.com/igniterealtime/openfire-pade-plugin/blob/master/ofgasi/classes/sip-communicator.properties

have fun :-)

**Comment by StreamerTag** [comment]
does editing that file ( https://github.com/igniterealtime/openfire-pade-plugin/blob/master/ofgasi/classes/sip-communicator.properties ) override anything that's configured in the UI?
I tried to edit the file and then rebuild the plugin and it didn't seem to have made any difference.

Also, if I can, would getting you a SIP server setup help?
I might be able to swing something.
