### ISSUE TITLE
Can't establish Audio/Video-streams using App Jitsi Meet 20.4.

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#76]
Establishing Audio/Video-streams using the _Jitsi Meet_ smartphone app fail with current version 20.4 on Android and iOS, both. Using the old 20.3, it still work as before. But the vanilla user can't downgrade to old versions, especially on iOS. Therefore, the App become unusable at the moment.

**Update**: The just released V87 of Chrome also drop TLS<1.2, therefore OFMeet becomes virtual unusable.

The problem is caused by a TLS problem on server side and should be solved by an upgrade to the current versions of the Bouncy Castle libs.

**Comment by gjaekel** [comment]
Thank you for support!

**Comment by gjaekel** [comment]
Unfortunately, updating BC libs on OpenFire don't help out. Running the provided snapshot openfire-4.6.1.20201020-1716, while connecting with the Jitsie Meet app I now got:
```
20201020-175844.008 ERROR [sPacketTransformer.connectThread] [n.j.s.c.u.UtilActivator] An uncaught exception occurred in thread=Thread[org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.connectThread,5,main] and message was: null
java.lang.NullPointerException: null
        at org.bouncycastle.crypto.tls.TlsUtils.PRF_legacy(Unknown Source) ~[?:?]
        at org.bouncycastle.crypto.tls.TlsUtils.PRF(Unknown Source) ~[?:?]
        at org.bouncycastle.crypto.tls.AbstractTlsContext.exportKeyingMaterial(Unknown Source) ~[?:?]
        at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.initializeSRTPTransformer(DtlsPacketTransformer.java:658) ~[libjitsi-1.0-0-gb3296cf.jar!/:?]
        at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1074) ~[libjitsi-1.0-0-gb3296cf.jar!/:?]
        at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$000(DtlsPacketTransformer.java:40) ~[libjitsi-1.0-0-gb3296cf.jar!/:?]
        at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$1.run(DtlsPacketTransformer.java:1272) ~[libjitsi-1.0-0-gb3296cf.jar!/:?]
```
As already stated, there also a bc lib in the OFMett plugin (`ofmeet/lib/bcprov-jdk15on-1.64.jar`). I try to replace it by the 1.66, and also ad the separated (D)TLS package `bctls-jdkon15-1.66`. But there's no success because of changed package names:
```
java.lang.NoClassDefFoundError: org/bouncycastle/crypto/tls/Certificate
        at org.jitsi.impl.neomedia.transform.dtls.DtlsControlImpl.generateCertificateInfo(DtlsControlImpl.java:390) ~[libjitsi-1.0-20190724.114721-390.jar!/:?]
```
because the location of the TLS Certificate Class have changed:
```
# unzip -l bcprov-jdk15on-1.64.jar._away | grep "/Certificate.class"
     2640  10-07-2019 11:26   org/bouncycastle/asn1/x509/Certificate.class
     2322  10-07-2019 11:26   org/bouncycastle/crypto/tls/Certificate.class                                                                                                                                                                                            20201020-181732
# unzip -l bcprov-jdk15on-1.66.jar | grep "/Certificate.class"
     2640  07-04-2020 15:47   org/bouncycastle/asn1/x509/Certificate.class                                                                                                                                                                                             20201020-181750
# unzip -l bctls-jdk15on-1.66.jar | grep "/Certificate.class"
     6095  07-04-2020 15:50   META-INF/versions/9/org/bouncycastle/tls/Certificate.class
     5096  07-04-2020 15:47   org/bouncycastle/tls/Certificate.class
```
From this I think, we need a newer version of this `libjitsi` (`libjitsi-1.0-20190724.114721-390.jar`) linked to `bc-1.66` ...

**Comment by deleolajide** [comment]
> From this I think, we need a newer version of this `libjitsi`

New version of libjitsi now causes JVB1.0 build to fail. I will tackle this over the weekend

**Comment by gjaekel** [comment]
what a mess ... 
Good luck!

**Comment by deleolajide** [comment]
> Good luck!

Thanks for the debugging and info provided. It is very useful.

**Comment by gjaekel** [comment]
Thank you for your investigations. In my eyes, the title of the blocking upstream issue don't represent the consequences in a proper way.

**Comment by ChicagoJay** [comment]
So, now that I have Pade up ad running, is this why the Jitsi app won't connect to my server?

**Comment by deleolajide** [comment]
> So, now that I have Pade up and running, is this why the Jitsi app won't connect to my server?

No. This is a different issue and can't be fixed until ofmeet is upgraded to use Jitsi Videobridge ver 2.x. [See this discussion](https://github.com/jitsi/jitsi-sctp/pull/3)

**Comment by gjaekel** [comment]
Dear Dele,
found a pull request that should JVB1 to provide TLS1.2 (https://github.com/riosu/libjitsi/pull/1). To my eyes, this might be working but was deferred in favor of switching to JVB2, too.

Would you please give this patch a chance, first? This might be a quick way to get more breath for the work to integrate JVB2!

**Comment by deleolajide** [comment]
> Would you please give this patch a chance, first? This might be a quick way to get more breath for the work to integrate JVB2!

Great idea. Thanks for finding this 👍 

I am working on both approaches. I spent yesterday evening on making libjitsi TLS1.2 compatible, but got blocked with a TLS handshake error. This weekend was going to be the upgrade if I can't fix it this evening.

I tried this patched libjitis, but it is too old and JVB1 gives an exception before we get to TLS. I don't want to regress to an April 2019 JVB. I might reapply the patch to latest more compatible libjitsi code
```
2020.11.20 07:33:13 ERROR [pool-8-thread-1]: net.java.sip.communicator.util.UtilActivator - An uncaught exception occurred in thread=Thread[pool-8-thread-1,5,main] and message was: org.jitsi.impl.neomedia.rtp.TransportCCEngine.<init>(Lorg/jitsi/utils/logging/DiagnosticContext;)V
java.lang.NoSuchMethodError: org.jitsi.impl.neomedia.rtp.TransportCCEngine.<init>(Lorg/jitsi/utils/logging/DiagnosticContext;)V
	at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:558) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:527) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.Conference.getTransportManager(Conference.java:1338) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.Channel.initialize(Channel.java:682) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:895) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.Content.createRtpChannel(Content.java:340) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:837) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:624) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.xmpp.XmppCommon.handleIQRequest(XmppCommon.java:192) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.xmpp.XmppCommon.handleIQInternal(XmppCommon.java:151) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.xmpp.XmppCommon.handleIQ(XmppCommon.java:122) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:221) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQSetImpl(ComponentImpl.java:320) ~[jitsi-videobridge-1.1-20201020.183027-125.jar!/:?]
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:362) ~[jicoco-1.1-4-g7c0752f.jar!/:?]
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:524) ~[tinder-2.0.0.jar:?]
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:291) ~[tinder-2.0.0.jar:?]
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239) ~[tinder-2.0.0.jar:?]
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:80) ~[tinder-2.0.0.jar:?]
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1058) ~[tinder-2.0.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_202]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
```

**Comment by deleolajide** [comment]
Applied patch to latest libjitsi code using bouncycastle 1.64. 
```
2020.11.20 08:45:07 ERROR [org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.connectThread]: org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer - Failed to connect this DTLS client to a DTLS server!
java.io.IOException: org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl is closed!
	at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.assertNotClosed(DatagramTransportImpl.java:124) ~[libjitsi-1.0-SNAPSHOT.jar!/:?]
	at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.send(DatagramTransportImpl.java:477) ~[libjitsi-1.0-SNAPSHOT.jar!/:?]
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.sendRecord(Unknown Source) ~[bcprov-jdk15on-1.64.jar!/:?]
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.send(Unknown Source) ~[bcprov-jdk15on-1.64.jar!/:?]
```
I also applied it to my changes libjitsi to make it work with BC 1.66 and I have the same handshake exception as before.
This closes the door on this approach. It is full speed on upgrade to JVB over the weekend

**Comment by gjaekel** [comment]
Thank you a lot for giving this a try.

At the moment, I try to get married OFMeeting with an external running JVB2. I patched the the hard-coded bridge name in `ConfigServlet.class` (with an hex-editor) to deliver 
```
  "hosts": {
[...]
    "bridge": "jitsi-videobridg2.<my-domainY"
[...]
  },
[...]
  "enforcedBridge": "jitsi-videobridg2.<my-domain>",
[...]
```
as `.../config.js` to the client, but it seems that this just important for the p2p-mode and I have to tell "jifoco" to use another bridge in some way.

```
20201120-100540.506 WARN  [k-Single Threaded Executor 0 (0)] [o.j.j.JitsiMeetConferenceImpl] The enforced bridge is not registered with BridgeSelector, will try to use a different one.
20201120-100540.509 INFO  [k-Single Threaded Executor 0 (0)] [o.j.j.b.BridgeSelectionStrategy] Selected initial bridge Bridge[jid=jitsi-videobridge.eval.xmpp.dnb.de, relayId=null, region=null, stress=0.00] with packetRate=0 for participantRegion=null

```
