### ISSUE TITLE
Can't seem to make the recording/live stream fuctionality work

### ISSUE THREAD

**Issue by StreamerTag** [igniterealtime/openfire-pade-plugin#85]
I'm using a docker image (for some reason installing it straight causes me even more issues) with host networking so in theory all the ports should be open and everything should just work.
(command docker run -v /root/mapped/openfire:/var/lib/openfire -e TZ=America/New_York  --network host  -d openfire:cuttingedge )

meetings work fine, as do most of the functionality.
however, whenever i try to do the recording or live stream functions, it just says "recording failed to start"
the addons i was using was a self-built (previous) latest from source (current latest won't pass the tests)

I THINK this is the relevant bit from the logs.
am i missing something?

2020.11.10 05:38:16 net.java.sip.communicator.impl.protocol.sip.SipLogger - Warning from the JAIN-SIP stackUsing default truststore type jks
2020.11.10 05:38:16 net.java.sip.communicator.impl.protocol.sip.SipLogger - Warning from the JAIN-SIP stackTLS trust settings will be inactive - TLS trust store will use JVM defaults. trustStoreType=jks javax.net.ssl.trustStore=null javax.net.ssl.trustStorePassword=null
2020.11.10 05:38:18 net.java.sip.communicator.service.resources.AbstractResourcesService - Missing resource for key: service.gui.ERROR
2020.11.10 05:38:18 net.java.sip.communicator.service.resources.AbstractResourcesService - Missing resource for key: plugin.reconnectplugin.CONNECTION_FAILED_MSG
2020.11.10 05:38:20 net.java.sip.communicator.service.resources.AbstractResourcesService - Missing resource for key: service.gui.ERROR
2020.11.10 05:38:20 net.java.sip.communicator.service.resources.AbstractResourcesService - Missing resource for key: plugin.reconnectplugin.CONNECTION_FAILED_MSG
2020.11.10 05:38:35 org.jitsi.jicofo.FocusManager - Jicofo ID is not set. Configure a valid value [1-65535] by setting org.jitsi.jicofo.SHORT_ID. Future versions will require this for Octo.
2020.11.10 05:38:36 org.jitsi.jicofo.FocusManager - No dedicated JVB MUC XMPP connection configured - falling back to the default XMPP connection
2020.11.10 05:38:38 org.jitsi.impl.protocol.xmpp.XmppProtocolProvider - The always_trust config option is enabled. All XMPP server provided certificates are accepted.
2020.11.10 05:38:43 org.jitsi.jicofo.xmpp.FocusComponent - (serving component 'Jitsi Meet Focus') Unexpected exception while processing IQ stanza: <iq type="get" id="368-25" from="component.redcateddomain.com" to="focus.redcateddomain.com"><query xmlns="jabber:iq:version"/></iq>
java.lang.IllegalArgumentException: name must not be null
        at org.jivesoftware.smack.util.StringUtils.requireNotNullOrEmpty(StringUtils.java:462) ~[smack-core-4.2.4-47d17fc.jar!/:?]
        at org.jivesoftware.smackx.iqversion.packet.Version.<init>(Version.java:71) ~[smack-extensions-4.2.4-47d17fc.jar!/:?]
        at org.jivesoftware.smackx.iqversion.packet.Version.<init>(Version.java:77) ~[smack-extensions-4.2.4-47d17fc.jar!/:?]
        at org.jitsi.jicofo.discovery.Version.<init>(Version.java:40) ~[jicofo-1.1-20200903.193811-189.jar!/:?]
        at org.jitsi.jicofo.discovery.VersionIqProvider.parse(VersionIqProvider.java:38) ~[jicofo-1.1-20200903.193811-189.jar!/:?]
        at org.jitsi.jicofo.discovery.VersionIqProvider.parse(VersionIqProvider.java:29) ~[jicofo-1.1-20200903.193811-189.jar!/:?]
        at org.jivesoftware.smack.provider.Provider.parse(Provider.java:43) ~[smack-core-4.2.4-47d17fc.jar!/:?]
        at org.jitsi.xmpp.util.IQUtils.convert(IQUtils.java:162) ~[jicoco-1.1-55-g3bc7f1d.jar!/:?]
        at org.jitsi.jicofo.xmpp.FocusComponent.handleIQGetImpl(FocusComponent.java:212) ~[jicofo-1.1-20200903.193811-189.jar!/:?]
        at org.jitsi.xmpp.component.ComponentBase.handleIQGet(ComponentBase.java:317) ~[jicoco-1.1-55-g3bc7f1d.jar!/:?]
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:520) ~[tinder-2.0.0.jar:?]
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:291) [tinder-2.0.0.jar:?]
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239) [tinder-2.0.0.jar:?]
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:80) [tinder-2.0.0.jar:?]
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1058) [tinder-2.0.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
2020.11.10 05:38:56 org.jitsi.xmpp.component.ComponentBase - PROCESSING TIME LIMIT EXCEEDED - it took 381ms to process: <iq id="eb98ba0a-62bb-4b14-8eca-d407bbea079c:sendIQ" to="focus.redcateddomain.com" type="set" from="admin@redcateddomain.com/9v22z9tlag"><conference xmlns="http://jitsi.org/protocol/focus" machine-uid="6381d8d6da64ea33ec3efe2a4cab23fc" room="111@conference.redcateddomain.com"><property name="enforcedBridge" value="jitsi-videobridge.redcateddomain.com"/><property name="channelLastN" value="-1"/><property name="disableRtx" value="false"/><property name="enableLipSync" value="false"/><property name="startBitrate" value="800"/><property name="openSctp" value="true"/><property name="startAudioMuted" value="9"/><property name="startVideoMuted" value="9"/><property name="stereo" value="false"/><property name="useRoomAsSharedDocumentName" value="false"/></conference></iq>
2020.11.10 05:38:59 org.ice4j.ice.Agent - Agent contains no IceMediaStream with name stream!

**Comment by deleolajide** [comment]
The ofmeet plugin does not support server-side recording with Jibri. I suggest you use the standalone Jitsi Meet application and use the docker instance provided by the Jitsi project.

![image](https://user-images.githubusercontent.com/110731/98676060-fdf64e00-2352-11eb-8484-4c358765552e.png)

Only client-side recording is supported like this

**Comment by StreamerTag** [comment]
Thats good to know.
ofmeet doesn't support live streaming either, i assume?

**Comment by deleolajide** [comment]
> ofmeet doesn't support live streaming either, i assume?

Server-side, no. You can however achieve it client side using a screen virtual webcam software for your O/S and then use OBS Studio or youtube.com/webcam to live stream from your virtual camera

**Comment by deleolajide** [comment]
If you only need video-conferencing and you are running Docker, just use the Jitsi Meet docker
