### ISSUE TITLE
Chorome 87 updated on November 17th disables audio and video from 3 users

### ISSUE THREAD

**Issue by naive924** [igniterealtime/openfire-pade-plugin#89]
We have actually confirmed the problem with 3 users, reproduction is possible by opening 3 tabs.
* Up to 2 tabs, I can hear the sound correctly.
	* The default behavior is to switch from 3 users to SFU and go through JVB.
* This problem does not occur with the original jitsi-meet using JVB2.
* Chrome 86 does not have this issue. Is this the cause?
	* Chrome 87 to remove support for non-standard RTP data channels in WebRTC https://www.techtsp.com/2020/08/chrome-87-remove-non-standard-rtp-data-channels-webrtc.html
![image](https://user-images.githubusercontent.com/6185430/99487996-c7e84800-29aa-11eb-9e85-09c874ee7931.png)

**Comment by gjaekel** [comment]
Thank you fro reporting this! May you provide a snippet of the all.log concerning the exception in communication? I expect a DTLS-error.

**Comment by gjaekel** [comment]
Is there still a TLS legacy switch (`chrome://flags/#legacy-tls-enforced`)?

**Comment by naive924** [comment]
I tried both enable / disable for `chrome://flags/#legacy-tls-enforced`, but the result is the same.
![image](https://user-images.githubusercontent.com/6185430/99501727-7f875500-29bf-11eb-8da6-ee7933cd8f5d.png)

**Comment by naive924** [comment]
>Thank you for reporting this! May you provide a snippet of the all.log concerning the exception in communication? I expect a DTLS-error.

Nothing may be recorded in all.log.
https://gist.github.com/naive924/51f60c34dbc4e57314c5e3a91b497ce3

**Comment by naive924** [comment]
Immediately after 3 users participated and switched to SFU.
It is recorded in error.log. The recall rate is 100%.

```
2020.11.18 17:12:48 org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer - Failed to connect this DTLS client to a DTLS server!
java.io.IOException: org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl is closed!
	at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.assertNotClosed(DatagramTransportImpl.java:124) ~[libjitsi-1.0-0-gb3296cf.jar!/:?]
	at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.send(DatagramTransportImpl.java:477) ~[libjitsi-1.0-0-gb3296cf.jar!/:?]
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.sendRecord(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.send(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSReliableHandshake$RecordLayerBuffer.sendToRecordLayer(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeHandshakeFragment(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeMessage(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.resendOutboundFlight(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.receiveMessage(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSClientProtocol.clientHandshake(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.bouncycastle.crypto.tls.DTLSClientProtocol.connect(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1006) [libjitsi-1.0-20190724.114721-390.jar!/:?]
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$000(DtlsPacketTransformer.java:40) [libjitsi-1.0-20190724.114721-390.jar!/:?]
	at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$1.run(DtlsPacketTransformer.java:1272) [libjitsi-1.0-20190724.114721-390.jar!/:?]

```

**Comment by gjaekel** [comment]
> Nothing may be recorded in all.log.
This is strage to me from the first lock.

>Immediately after 3 users participated and switched to SFU.
>It is recorded in error.log. The recall rate is 100%.

I guess you have peer-2-peer mode for two clients enabled. If you disable, you should get it from the first.
Now I see the well-known; bc*1.64 can't handle this.

I' busy at work, I'll  take a look on it later.

**Comment by naive924** [comment]
This error does not occur with Chrom86(lower) or  Edeg with more than 3 users joining.
`
2020.11.18 17:12:48 org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer - Failed to connect this DTLS client to a DTLS server!
java.io.IOException: org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl is closed!
`

**Comment by gjaekel** [comment]
For me, it still works using `Chromium Version 86.0.4240.198 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)`

**Comment by naive924** [comment]
If you update to Chrom87, you will run into the same problem.
![image](https://user-images.githubusercontent.com/6185430/99632192-29c6b180-2a80-11eb-9f59-9b40d4dcf34a.png)

**Comment by naive924** [comment]
Hi @deleolajide 
Please tell me!

This problem is the same as https://github.com/igniterealtime/openfire-pade-plugin/issues/76#issuecomment-729203696, can't it be solved until JBV2 upgrade?

The difference from issues76 is that the Jitsi Meet version happens bundled with ofmeet.jar.

**Comment by deleolajide** [comment]
> This problem is the same as [#76 (comment)](https://github.com/igniterealtime/openfire-pade-plugin/issues/76#issuecomment-729203696), can't it be solved until JBV2 upgrade?

It is the same problem. Chrome 87 has the same breaking change to JVB1 as first seen with the mobile apps. It has something to do with TLS 1.0 and 1.1 removal

**Comment by gjaekel** [comment]
> It has something to do with TLS 1.0 and 1.1 removal

and the TLS layer of the client is provided by the __browser__, but not by the downloaded (js-)code of the client.

**Comment by naive924** [comment]
Thank you for your reply!
What time is the JBV2 upgrade for the openfire-pade-plugin scheduled?

This is one of my most focused cases, and I would like to cooperate with testing and other investigations..

**Comment by deleolajide** [comment]
Please test [new pre-release version 1.1.0](https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.1.0) and confirm if it works for you.

**Comment by naive924** [comment]
Hi @deleolajide 

Congratulations on JVB2 support!! 

I checked [new pre-release version 1.1.0](https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.1.0), but the focus doesn't seem to go online.
![image](https://user-images.githubusercontent.com/6185430/99926813-4e739f80-2d86-11eb-963d-4b9dd1eb43ea.png)

all.log contains a `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException`.
Is there anything I need to consider about self-signed ssl in this new version(1.1.0)?


- Environment
OS : Windows64bit
ofmeet URL: https://pc:7443/ofmeet (For local testing)
Java: OpenJDK 64-Bit Server VM Corretto-8.252.09.2 (build 25.252-b09, mixed mode)
Openfire: openfire_4_6_0

- Error
```
Jicofo 2020-11-23 11:47:23.234 重大: [28] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
org.jivesoftware.smack.SmackException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1076)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1688)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:810)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1200(XMPPTCPConnection.java:151)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1071)
	... 3 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
	... 13 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
	... 19 more

```

**Comment by SamGanab** [comment]
@deleolajide Hi Dale!

First off, we greatly appreciate the amazing work you put forth!

I can confirm with @naive924 that connectivity/online issues exist between the jvb & focus user (for me, neither appear online).

Server environment: Windows 2016 Datacenter
Test environment: Windows 10 Pro

Thank you,
Sam.

**Comment by naive924** [comment]
Is this the cause? 
https://github.com/jitsi/jitsi-videobridge/issues/1402

The following fixes also seem to fix the Chorome 87 issue.
```
diff --git a/offocus/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJicofoWrapper.java b/offocus/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJicofoWrapper.java
index e7d3158..1ce7154 100644
--- a/offocus/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJicofoWrapper.java
+++ b/offocus/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJicofoWrapper.java
@@ -93,6 +93,9 @@ public class JitsiJicofoWrapper implements ProcessListener
         props.setProperty( "net.java.sip.communicator.service.gui.ALWAYS_TRUST_MODE_ENABLED", "true");;
         props.setProperty( "org.jitsi.jicofo.PING_INTERVAL", "-1" );
         props.setProperty( "org.jitsi.jicofo.SERVICE_REDISCOVERY_INTERVAL", "-1" );
+        props.setProperty( "org.jitsi.jicofo.ALWAYS_TRUST_MODE_ENABLED", "true" );
         props.store(new FileOutputStream(props_file), "Properties");


diff --git a/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/OfMeetPlugin.java b/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/OfMeetPlugin.java
index 6647ad9..5719202 100644
--- a/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/OfMeetPlugin.java
+++ b/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/OfMeetPlugin.java
@@ -312,6 +312,8 @@ public class OfMeetPlugin implements Plugin, SessionEventListener, ClusterEventL
         System.setProperty( "net.java.sip.communicator.service.media.DISABLE_AUDIO_SUPPORT", "true" );
         System.setProperty( "net.java.sip.communicator.service.media.DISABLE_VIDEO_SUPPORT", "true" );

+        System.setProperty("org.jitsi.videobridge.xmpp.user.SHARD.DISABLE_CERTIFICATE_VERIFICATION", "true" );
```

**Comment by SamGanab** [comment]
@naive924 Hey!

Were you able to resolve the issue with JVB & Focus generated users not connection on 1.1.0 pre-release?

Thank you!
Sam.

**Comment by gjaekel** [comment]
> Is there anything I need to consider about self-signed ssl in this new version(1.1.0)?

It's off-topic concerning the Video Bridge or other changes. But -- already with the older versions -- you can't use the _Jitsi Meeting_ Smartphone App in conjunction with a self-signed certificate at the server, because it will not accept this.

**Comment by naive924** [comment]
@gjaekel 
> you can't use the Jitsi Meeting Smartphone App in conjunction with a self-signed certificate at the server, because it will not accept this.

Thank you, I understand.

@deleolajide
Can you tell me. "Not Secure" is displayed in deleolajide 's address bar. Is it self-signed ssl?
https://user-images.githubusercontent.com/110731/99916499-69043500-2d02-11eb-90e9-234d618e66ed.png

I think the advantage of openfire-pade-plugin is that it can be developed on local Windows, so it would be nice to have the self-signed ssl option. I'm avoiding it this way(https://github.com/jitsi/jitsi-videobridge/issues/1402) for the time being.

**Comment by deleolajide** [comment]
Finally working with Linux in Docker with NAT. See https://github.com/igniterealtime/openfire-pade-plugin/issues/88#issuecomment-733037130

**Comment by deleolajide** [comment]
> Can you tell me. "Not Secure" is displayed in deleolajide 's address bar. Is it self-signed ssl?

Yes, it is self-signed on my dev pc. You can open web pages in Chrome with not secure because chrome will ask you to confirm  it. That may not the be the case in a app that does use an API like Jitsi mobile app does

**Comment by gjaekel** [comment]
> That may not the be the case in a app that does use an API like Jitsi mobile app does

IMHO this *is* the case, I had to acquire trusted certificates for my xmpp server instances for this reason.

**Comment by ClaudeStabile** [comment]
![screenshot65](https://user-images.githubusercontent.com/29485972/100134038-e2796000-2e87-11eb-8e40-67e95f28585f.png)
@deleolajide Chrome 87 is now working fine with latest ofmeet plugins. Docker mode. Working also with Firefox now
with updated plugins @ https://www.free-solutions.org 
Thanks a lot for efforts fixing this

**Comment by naive924** [comment]
With  [v1.1.1](https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.1.1), `PKIX path building failed`  also doesn't seem to occur.
* PKIX  issue  https://github.com/igniterealtime/openfire-pade-plugin/issues/89#issuecomment-731908417

I have tried it in a Windows local network environment and everything is good.
